apiVersion: apps/v1
kind: Deployment
metadata:
  name: mrdd-va-rasa-full-deployment
  namespace: biocomplexity
  labels:
    app: mrdd-va-rasa-full
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mrdd-va-rasa-full
  template:
    metadata:
      labels:
        app: mrdd-va-rasa-full
    spec:
      containers:
      - name: mrdd-va-rasa-full-container
        image: ghcr.io/nssac/mrdd-va-rasa-server-chatbot:{{ .Values.version.rasaFull }}
        command: ["rasa"]
        args: ["run", "--enable-api","--endpoints","endpoints.yml","--cors","*","-m","models","--debug"]
        # True command in docker:
        # rasa run --enable-api --endpoints endpoints.yml --cors * -m models --debug
        ports:
        - containerPort: 5005
        env:
        - name: KEY
          value: "value"
        resources:
          requests:
            memory: "1024Mi"
            cpu: "1000m"
          limits:
            memory: "2048Mi"
            cpu: "1000m"
