apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: xwiki-nginx-ingress
  namespace: biocomplexity
spec:
  rules:
    - host: sdad-xwiki.pods.uvarc.io
      http:
        paths:
          - backend:
              serviceName: xwiki-service
              servicePort: 8080
            path: /


