apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xwiki-nfs-pvc
  namespace: biocomplexity
spec:
  storageClassName: xwiki-sc
  accessModes:
    - ReadWriteMany  #must be the same as PersistentVolume
  resources:
    requests:
      storage: 10Gi
