apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stoplabel-prod-nfs-pvc
  namespace: biocomplexity
spec:
  storageClassName: stoplabel-prod-sc
  accessModes:
    - ReadWriteMany  #must be the same as PersistentVolume
  resources:
    requests:
      storage: 10Gi
