apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: stormshare-prod-nginx-ingress
  namespace: biocomplexity
spec:
  rules:
    - host: stormshare-prod.pods.uvarc.io
      http:
        paths:
          - backend:
              serviceName: stormshare-prod-service
              servicePort: 8080
            path: /


