apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bii-pgadmin-pvc
  namespace: biocomplexity
spec:
  storageClassName: bii-pgadmin-sc
  accessModes:
    - ReadWriteMany  #must be the same as PersistentVolume
  resources:
    requests:
      storage: 10Gi
