apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bii-pgadmin-nfs-pvc-2
  namespace: biocomplexity
spec:
  storageClassName: bii-pgadmin-sc-2
  accessModes:
    - ReadOnlyMany  #must be the same as PersistentVolume
  resources:
    requests:
      storage: 10Gi
