apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fox-bii-dsc-infomall-nfs-pvc
  namespace: biocomplexity
spec:
  storageClassName: fox-bii-dsc-infomall-sc
  accessModes:
    - ReadWriteMany  #must be the same as PersistentVolume
  resources:
    requests:
      storage: 10Gi
