apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgrest-test-deployment
  namespace: biocomplexity
  labels:
    app: postgrest-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgrest-test
  template:
    metadata:
      labels:
        app: postgrest-test
    spec:
      volumes:
      - name: postgrest-test-nfs-volume
        persistentVolumeClaim:
          claimName: postgrest-test-nfs-pvc # name of pvc
      containers:
      - name: postgrest-test-container
        image: postgrest/postgrest
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: postgrest-test-nfs-volume
          mountPath: /etc/postgrest.conf # mount inside of container
        env:
        - name: PGRST_DB_POOL_TIMEOUT
          value: "10"
        - name: PGRST_LOG_LEVEL
          value: "info"
        - name: PGRST_DB_POOL
          value: "10"
        resources:
          requests:
            memory: "2024Mi"
            cpu: "50m"
          limits:
            memory: "3024Mi"
            cpu: "100m"
            

# biocomplexity/postgrest-db_anon_role
# Environment Name
# PGRST_DB_ANON_ROLE

# biocomplexity/postgrest-db_connection
# Environment Name
# PGRST_DB_URI

# biocomplexity/postgrest-db_schema
# Environment Name
# PGRST_DB_SCHEMA
